name: pyrmm
dependencies:
  - python=3
  - ipython     # convenience
  - pytest      # package testing
  - hypothesis  # package testing
  - nb_conda
  - git
  - pip
  - pip:
    - -e . # this package
    - -r requirements.txt