name: pyrmm
channels:
  - conda-forge
dependencies:
  - python=3.8  # pcg-gazebo has errors with libgeos and collections in 3.10 (3.9 not tested)
  - pyvips      # necessary as conda install to avoid further library setups from pip install
  - libvips
  - libffi
  - cffi
  - ipython     # convenience
  - pytest      # package testing
  - hypothesis  # package testing
  - nb_conda    # jupyter notebooks
  - git
  - pip
  - pip:
    - -e . # this package
    - -r requirements.txt # dependencies of top-level package
    - -r src/pyrmm/environments/requirements.txt  # dependencies of quasi-independent "environments" subpackage